env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/vue3-strongly-recommended'
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules: {}
