name: eslint
on:
  pull_request:
    branches: [ main, develop ]
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: yarn install
        run: yarn install
        working-directory: ./app
      - uses: reviewdog/action-setup@v1
      - name: Run eslint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn run lint | reviewdog -f=eslint -reporter=github-pr-review -filter-mode=diff_context -fail-on-error=true
        working-directory: ./app
